language: perl
perl:
  - "5.10"
  - "5.18"
  - "5.20"

before_install:
  - cpanm Carton
install:
  - carton install
script:
  - carton exec prove -lrv t

notifications:
  emails:
    - mihyaeru21@gmail.com
  on_success: always
  on_failure: always

