language: perl
perl:
  - "5.10"
  - "5.18"
  - "5.20"

before_install:
  - cpanm -n git://github.com/kan/coveralls-perl.git
script: perl Build.PL && make && cover -test
after_success:
  - cover -report coveralls

notifications:
  emails:
    - mihyaeru21@gmail.com
  on_success: always
  on_failure: always

